sudo: false
os: linux
jobs:
  include:
    language: c
    script:
      - make -f ./src/c/Makefile
      - ./src/c/hello_world
    language: java
    script:
      - make -f ./src/java/Makefile
      - java -cp src/java/ HelloWorld
    language: elm
    script:
      - cd src/elm && make
    language: java
    script:
      - curl -s https://get.sdkman.io | bash
      - source "/home/travis/.sdkman/bin/sdkman-init.sh"
      - sdk install kotlin
      - cd src/kotlin && make
      - java -jar src/kotlin/hello_world.jar
