sudo: false
os: linux
jobs:
  include:
    # C
    - language: c
      script:
        - make -f ./src/c/Makefile
        - ./src/c/hello_world
    # Java
    - language: java
      script:
        - make -f ./src/java/Makefile
        - java -cp src/java/ HelloWorld
    # Elm
    - language: elm
      script:
        - cd src/elm && make
    # Kotlin
    - language: java
      jdk:
        - oraclejdk9
      script:
        - curl -s https://get.sdkman.io | bash
        - source "/home/travis/.sdkman/bin/sdkman-init.sh"
        - sdk install kotlin
        - make -f ./src/kotlin/Makefile
        - java -jar ./src/kotlin/hello_world.jar
    # Prolog
    - language: bash
      install:
        - sudo apt-get install gprolog    
      script:
        - make -f ./src/prolog/Makefile
        - ./src/prolog/hello_world
    # C++
    - language: cpp
      compiler:
        - gcc
      script:
        - make -f ./src/cpp/Makefile
        - ./src/cpp/hello_world
    # Go
    - language: go
      go:
        - 1.10.4
      script:
        - make -f ./src/go/Makefile
        - ./src/go/hello_world
    # Cobol
    - language: bash
      install:
        - sudo apt-get install open-cobol
      script:
        - make -f ./src/cobol/Makefile
        - ./src/cobol/hello_world
    # Scala
    language: scala
      script:
        - make -f ./src/scala/Makefile
        - ./src/scala/hello_world
