sudo: false
matrix:
  include:
    language: c
    script:
      - make -f ./src/c/Makefile
      - ./src/c/hello_world
    language: java
    script:
      - make -f ./src/java/Makefile
      - java -cp src/java/ HelloWorld
    language: elm
    script:
      - cd src/elm && make
