name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: c-compile
      run: |
        make -f ./src/c/Makefile
        ./src/c/hello_world
    - name: elm-compile
      run: |
        sudo apt-get update
        sudo apt-get install npm
        sudo npm install elm --global
        cd ./src/elm && make

    - name: java-compile
      run: |
        make -f ./src/java/Makefile
        java -cp src/java/ HelloWorld

